### ISSUE TITLE
get_submission double counts

### ISSUE THREAD

**Issue by stillmatic** [daranzolin/rcanvas#4]
manually stepping through the code, i have the following for `other_pages`:

```
> other_pages
[1] "https://canvas.upenn.edu/api/v1/courses/XXX/assignments/YYY/submissions?page=1&per_page=100>"
```

this returns the same as the first step through; probably because it's page 1. maybe for your canvas installation other_pages returns nothing? trying this again with an assignment where 143 submissions were received, the `get_submissions` returns 243 entries. so it appears that the first page is always being double counted.

couple possible fixes:

1. change `other_pages` logic to > 1
2. check and only return unique values at the end

if your canvas installation's behavior is to not return the first page in 'other pages' then we should use approach 2. if you can replicate my error, we should use approach 1.

**Comment by daranzolin** [comment]
Ah, I think I spot the error. The line should read: `other_pages <- get_pages(resp)[-1]`, not `other_pages <- get_pages(resp)`. Forgot to omit the first item, which is the first page url.

I'll push an update later today and see if that fixes it.

**Comment by stillmatic** [comment]
it actually seems like you don't need to parse the first page. you can get the response, see if there are any pages, then use the purrr-based mapping to get the data for each page.

happy to make a PR for this if the logic sounds reasonable.

**Comment by daranzolin** [comment]
That logic does sound reasonable and would probably make for more concise code, but wouldn't that slow the function down by making a redundant request? Like, we make the initial GET request, extract the pages, then make GET requests for each page, including the first page for which we already have in the response? I think that's what I was trying to avoid originally.

**Comment by stillmatic** [comment]
In that case, maybe what we can do is only request the header from the GET request; this should be a cheap request. If there is no item, then it will be immediately clear; and if there is only one page, it will be only a little bit more expensive. 

example:

```
$ curl -s -D - https://canvas.upenn.edu/api/v1/[...] -o /dev/null

HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Wed, 21 Dec 2016 00:59:19 GMT
ETag: W/"[...]"
Link: <https://canvas.upenn.edu/api/v1/[...]?page=1&per_page=10>; rel="current",<https://canvas.upenn.edu/api/v1/[...]?page=2&per_page=10>; rel="next",<https://canvas.upenn.edu/api/v1/[...]?page=1&per_page=10>; rel="first",<https://canvas.upenn.edu/api/v1/[...]?page=15&per_page=10>; rel="last"
P3P: CP="None, see http://www.instructure.com/privacy-policy"
Server: Apache
[ other headers ]
```

At any rate, this also implies that we could miss pages here; since there are 15 pages but only 3 unique ones are included in the link header. With the current setup, this would return incomplete results for items with 300+ submissions/students/etc. I guess you can do some parsing, so go from pages 1 to 15 here, but maybe the easier thing to do is just bump the per-page argument to something absurdly high (unless Canvas doesn't allow that, in which case we would need to write a parser).

**Comment by daranzolin** [comment]
Okay, did you have something like this in mind?

```
get_submissions <- function(course_id, type, type_id) {
  if (!type %in% c("quizzes", "assignments")) stop("type must be 'quizzes' or 'assignments'")
  url <- sprintf("%scourses/%s/%s/%s/submissions", canvas_url(), course_id, type, type_id)
  args <- list(access_token = check_token(),
               per_page = 100)
  req <- httr::HEAD(url, query = args)
  get_pages(httr::headers(req)$link %>% #iterates through every unique page, unless we change behavior of get_pages()
    purrr::map(canvas_query, args) %>%
    purrr::map(httr::content, "text") %>%
    purrr::map(jsonlite::fromJSON, flatten = TRUE)
}
```
 And hmmm, I don't see how we'd lose pages by only capturing the unique pages.

**Comment by stillmatic** [comment]
Yeah, I think that that makes the most sense, and I didn't actually realize httr had a head function (!). Ideally, we'd abstract most of that to a helper function but it looks a lot cleaner (I think everything from `req <- httr::HEAD(...)` on is duplicated in a bunch of places).

Let's say we have a class and there are 301 students, each of whom turn in an assignment, so we have 301 submissions. Then, we need 4 pages to represent this: 1-100, 2-200, 3-300, 301. The 'Link' parameter in the header has 4 links: current, next, first, last (maybe previous too, if we queried page 2 or something). These will map out to:

* Current: Page 1
* Next: 2
* First: 1
* Last: 4

The way `get_pages` is written, we would return pages 1, 2, and 4 - leaving out 3.

What is possible then is to parse out what index the last page is (here, 4), and then construct the url's for each page. We would have a vector from 1:4 essentially.

**Comment by daranzolin** [comment]
You're 100% right, I see it now. 

I haven't formally tested this yet, but the modification below to `get_pages()` might do the trick. `n_pages` should return the number of the last page, then we build up the pages from that vector.

```
get_pages <- function(x) {
  pages <- httr::headers(x)$link
  stopifnot(!is.null(pages))
  pages <- stringr::str_split(pages, ";")[[1]]
  url_pattern <- "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
  pages <- purrr::map_chr(pages, stringr::str_extract, url_pattern)
  pages <- unique(pages[!is.na(pages)])
  base_url <- unique(pages[!is.na(pages)])[1]
  n_pages <- readr::parse_number(stringr::str_extract(pages[length(pages)], "page=[0-9]{1,}"))
  pages <- str_replace(base_url, "page=[0-9]", sprintf("page=%s", 1:n_pages))
  return(pages)
}
```

**Comment by stillmatic** [comment]
👍 lgtm

**Comment by daranzolin** [comment]
Alas, the above solution is inadequate, [as explained in the pagination documentation here.](https://canvas.instructure.com/doc/api/file.pagination.html) I quote: 

> rel="last" may also be excluded if the total count is too expensive to compute on each request.

I've reworked `get_submissions()` and a new helper function, `get_next_page()` on a separate branch and would like to hear your thoughts before I merge the changes. The idea here is to keep checking to see if there's a "next" page, and then stash the responses into a list. I've been programming in R for about two years now, and this was my first while-loop, and it looks hideous, but I think it does the job. If you think there's a better way, by all means, feel free to make a PR.

`get_next_page():`
```
get_next_page <- function(resp) {
  pages <- httr::headers(resp)$link
  if (is.null(pages)) {
    return(FALSE)
  }
  next_page_exists <- stringr::str_detect(pages, "next")
  if (next_page_exists) {
    pages <- stringr::str_split(pages, ",")[[1]]
    url_pattern <- "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))*"
    next_page <- stringr::str_subset(pages, "next")
    next_page <- stringr::str_extract(next_page, url_pattern)
    next_page <- stringr::str_sub(next_page, end = -3L)
  } else {
    return(FALSE)
  }
  next_page
}
```

new `get_submissions():`

```
get_submissions <- function(course_id, type, type_id) {
  if (!type %in% c("quizzes", "assignments")) stop("type must be 'quizzes' or 'assignments'")
  url <- sprintf("%s/courses/%s/%s/%s/submissions", canvas_url(), course_id, type, type_id)
  args <- list(access_token = check_token(),
               per_page = 10)
  resp <- canvas_query(url, args, httr::GET)
  dat_list <- list(resp)
  next_page <- get_next_page(resp)
  i <- 2
  x <- 1
  while (x < 4) {
    dat <- canvas_query(next_page, args, httr::GET)
    dat_list[[i]] <- dat
    next_page <- get_next_page(dat)
    if (!isTRUE(next_page)) {
      x <- x + 1
    }
    i <- i + 1
  }
  dat_list %>%
    purrr::map(httr::content, "text") %>%
    purrr::map(jsonlite::fromJSON, flatten = TRUE) %>%
    purrr::map_df(purrr::flatten_df)
}
```

**Comment by stillmatic** [comment]
Yeah, this is actually pretty annoying. I'm trying to come up with a nicer way to do the `get_submissions` step. 

One immediate improvement would be to check the link headers and see if there's a `"rel=\"last\""` entry. Then, we have a firm `n_pages` bound and can avoid the other stuff.

My other general idea is to create a `has_next` function, which takes a given url's http response and checks for the next page flag.
