### ISSUE TITLE
error in get_course_list in course-data.R 

### ISSUE THREAD

**Issue by gqmaguirejr** [daranzolin/rcanvas#8]
There is a missing assignment to dat before returning dat as a value.
The code should be:
get_course_list <- function(user_id = NULL, include = NULL) {
  if (!is.null(user_id)) {
    url <- paste0(canvas_url(), paste("users", user_id, "courses", sep = "/"))
  } else {
    url <- paste0(canvas_url(), "courses")
  }
  args <- list(access_token = check_token(),
               per_page = 100,
               user_id = user_id)
  include <- iter_args_list(include, "include[]")
  args <- c(args, include)
  dat <- process_response(url, args)   # there must be an assignment of the returned data frame to dat
  return(dat)
}

**Comment by daranzolin** [comment]
Thanks for the heads up--should be fixed now.
